Repository VirtusLab-Open-Source/strapi-plugin-navigation, pull requests merged in 2025-05, with the labels that each got.

#554 fix: additional boolean fields db migration
  migrations/strapi-plugin-navigation-3.0.0-no-4-additional-fields.js
Labels: bug

#556 fix: migration service id in first migration
  migrations/strapi-plugin-navigation-3.0.0-no-1-related-id-to-documentid.js
Labels: bug

#559 fix: remove i18n
  README.md
  server/src/config/index.ts
Labels: documentation

#564 fix: fix order of first migration
  migrations/strapi-plugin-navigation-3.0.0-no-1-related-id-to-documentid.js
  server/src/bootstrap.ts
  server/src/repositories/navigation-item.ts
  server/src/services/migration/migration.ts
Labels: bug, v4, maintenance
